### ISSUE TITLE
Change width while drawing

### ISSUE THREAD

**Issue by Coriou** [kmkzt/react-hooks-svgdrawing#4]
Delightful library, thank you so much !

I was playing with it and I thought I'd be cool to add [Pressure.JS](https://github.com/stuyam/pressure) to it, especially when drawing with an Apple Pencil to change the width of the pencil based on the pressure applied.

I got a working prototype, however the pencil size will only change between mouse/touch end/start events.

I was wondering if it was somehow possible to change the pencil size even while drawing ?

**Comment by kmkzt** [comment]
Thank you for the information.
I will try to update the sample code using Pressure.JS and try it.

I'm sorry because I can not know without trying it about the problem that I can not change the thickness of the pen while drawing.

Perhaps I will add an onMousemove event with a process that changes the thickness of the pen.

**Comment by Coriou** [comment]
Thanks !

Here's a (dirty) implementation I'm working on if you want to have a look at it right now (includes Pressure.JS): https://bc-drawing.surge.sh

**Comment by kmkzt** [comment]
Update to enable changing pen settings while drawing.

You will find that you can see the [demo](https://kmkzt.github.io/react-hooks-svgdrawing/) content of the [example](https://github.com/kmkzt/react-hooks-svgdrawing/blob/master/src/example/index.tsx).
Implemented to become thinner and thinner pen using the library you have been taught.

**Comment by Coriou** [comment]
Wow, that's amazing thanks. Thank you for updating the color changing while drawing too :)
